version: "3.9"

services:
  rag_api:
    build: .
    container_name: oxylabs-rag-api
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - chroma_data:/data
    restart: unless-stopped
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000

volumes:
  chroma_data:
    driver: local
